import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.event.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class StartScreen extends JFrame {
	private int flockSize = 100;
	private int width = 1200;
	private int height = 900;
	private JSlider flockSizeSlider;
    private JLabel flockSizeLabel;
    private JPanel panel;
    private JButton startButton;
    private JLabel titleLabel;
    private Image backgroundImg, scaledImg;

	public StartScreen() {
		// Container c =  getContentPane();
		// c.setLayout(new SpringLayout());

		// JLabel swarmLabel = new JLabel("pseudo experimental music generator");
		// JSlider flockSizeSlider = new JSlider(2, 242, 100);
		// JButton startButton = new JButton("Start");

		// flockSizeSlider.addChangeListener(new ChangeListener() {
		// 	public void stateChanged(ChangeEvent e) {
		// 		JSlider source = (JSlider)e.getSource();
		// 		flockSize = (int)source.getValue();
  //     		}
  // 		});
		// startButton.addActionListener(new ActionListener()
		// {
		// 	public void actionPerformed(ActionEvent e)
		// 	{
		// 		Simulator sim = new Simulator(flockSize);
		// 		sim.setVisible(true);
		// 		setVisible(false);
		// 	}
		// });

		// // swarmLabel.setMaximumSize(new Dimension(300,100));
		// // flockSizeSlider.setMaximumSize(new Dimension(80, 10));
		// // startButton.setMaximumSize(new Dimension(40,20));

		// c.add(swarmLabel);
		// c.add(flockSizeSlider);
		// c.add(startButton);
		try {                
          backgroundImg = ImageIO.read(new File("perlin2.png"));
          scaledImg = backgroundImg.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        }
        catch (IOException e){}

		initComponents();
		setSize(width, height);
		setResizable(false);
		setTitle("pseudo experimental music generator");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		//pack();
		setVisible(true);
	}

	private void initComponents() {
		//method initially generated by netbeans swing gui form
        panel = new Background();
        titleLabel = new JLabel();
        startButton = new JButton("start");
        flockSizeSlider = new JSlider();
        flockSizeLabel = new JLabel("uhh how many particles you need?");

        titleLabel.setFont(new Font("Lucida Sans", 0, 48)); 
        titleLabel.setForeground(new Color(242,242,242));
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setText("pseudo experimental music generator");

        startButton.setBackground(new Color(242,242,242));
        startButton.setFont(new Font("Lucida Sans", 0, 24)); 
        startButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Simulator sim = new Simulator(flockSize);
				sim.setVisible(true);
				setVisible(false);
            }
        });

        flockSizeSlider.setFont(new Font("Calibri", 0, 16)); 
        flockSizeSlider.setBackground(new Color(40,40,40));
        flockSizeSlider.setForeground(new Color(222,222,222));
        flockSizeSlider.setMajorTickSpacing(100);
        flockSizeSlider.setMaximum(242);
        flockSizeSlider.setMinimum(10);
        flockSizeSlider.setMinorTickSpacing(10);
        flockSizeSlider.setPaintLabels(true);
        flockSizeSlider.setPaintTicks(true);
        flockSizeSlider.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				JSlider source = (JSlider)e.getSource();
				flockSize = (int)source.getValue();
      		}
  		});

        flockSizeLabel.setFont(new Font("Lucida Sans", 0, 21)); 
        flockSizeLabel.setForeground(new Color(222,222,222));
        flockSizeLabel.setHorizontalAlignment(SwingConstants.CENTER);

        GroupLayout panelLayout = new GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(flockSizeLabel, GroupLayout.PREFERRED_SIZE, 455, GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
            .addGroup(GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(flockSizeSlider, GroupLayout.PREFERRED_SIZE, 434, GroupLayout.PREFERRED_SIZE)
                        .addGap(380, 380, 380))
                    .addGroup(GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(startButton, GroupLayout.PREFERRED_SIZE, 234, GroupLayout.PREFERRED_SIZE)
                        .addGap(480, 480, 480))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(titleLabel, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(flockSizeLabel, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flockSizeSlider, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(startButton, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

		GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);        
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    class Background extends JPanel {
    	@Override
    	public void paintComponent(Graphics g) {
      		super.paintComponent(g);
      		g.drawImage(scaledImg, 0, 0, null);
      	}
     }

	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {new StartScreen();}
		});
	}
}
